name: Release for 1.x

on:
  push:
    branches: [ 1.x ]

jobs:
  release:
    name: NPM
    uses: node-modules/github-actions/.github/workflows/npm-release.yml@master
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
